/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TB_040_048;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TB_040_048.koneksi;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import TB_040_048.EMapel;
import TB_040_048.cCari;

/**
 *
 * 
 */
public class Form_MaPel extends javax.swing.JFrame {

    /**
     * Creates new form Form_MatKul
     */
    public Form_MaPel() {
        initComponents();
        tabelmatkul();
        tampil_combo();
    }
    
     public void tampil_combo()
    {
        
      
        try {
        Connection conn = koneksi.getConnection();
        Statement sttm = conn.createStatement();
        String sql = "select NIP from GUru order by NIp asc";      // disini saya menampilkan NIM, anda dapat menampilkan
        ResultSet reslt = sttm.executeQuery(sql);                                // yang anda ingin kan
        
        while(reslt.next()){
            Object[] ob = new Object[3];
            ob[0] = reslt.getString(1);
            
            comboGURU.addItem(ob[0]);                                      // fungsi ini bertugas menampung isi dari database
        }
        reslt.close(); sttm.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void tabelmatkul(){
        DefaultTableModel tabbrg = new DefaultTableModel();
        tabbrg.addColumn("NO Mata Pelajaran");
        tabbrg.addColumn("Nama Mata Pelajaran");
        tabbrg.addColumn("NIP");
        
        jTable1_tabmatkul.setModel(tabbrg);
        
        try {
            Statement stat = (Statement)koneksi.getConnection().createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM MAPEL order by no_mapel asc");
            while (result.next()){
                tabbrg.addRow(new Object[]{
                    result.getString("NO_MAPEL"),
                    result.getString("NAMA_MAPEL"),
                    result.getString("NIP"),              
                });
                jTable1_tabmatkul.setModel(tabbrg);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditampilkan");
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_idmatkul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2_namamatkul = new javax.swing.JTextField();
        B_TAMBAH = new javax.swing.JButton();
        B_HAPUS = new javax.swing.JButton();
        B_EDIT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        B_RESET = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabmatkul = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        comboGURU = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MATA PELAJARAN");

        jLabel2.setText("NO Mata Pelajaran");

        jLabel3.setText("Nama Mata Pelajaran");

        B_TAMBAH.setText("TAMBAH");
        B_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TAMBAHActionPerformed(evt);
            }
        });

        B_HAPUS.setText("HAPUS");
        B_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HAPUSActionPerformed(evt);
            }
        });

        B_EDIT.setText("EDIT");
        B_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EDITActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        B_RESET.setText("RESET");
        B_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RESETActionPerformed(evt);
            }
        });

        jTable1_tabmatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_tabmatkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_tabmatkulMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_tabmatkul);

        jLabel4.setText("NIP");

        comboGURU.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guru" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(B_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_idmatkul, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jTextField2_namamatkul)
                                    .addComponent(comboGURU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_idmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2_namamatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboGURU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_TAMBAH)
                    .addComponent(B_EDIT)
                    .addComponent(B_HAPUS)
                    .addComponent(B_RESET))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TAMBAHActionPerformed
    EMapel matkul = new EMapel();
    matkul.setidmpel(jTextField1_idmatkul.getText());
    matkul.setnamamapel(jTextField2_namamatkul.getText());
    matkul.setnip(comboGURU.getItemAt(comboGURU.getSelectedIndex()).toString());
    
    cCari control = new cCari();
    control.tambahmatkul(matkul);
    tabelmatkul();
       B_RESETActionPerformed(evt);
    }//GEN-LAST:event_B_TAMBAHActionPerformed

    private void B_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EDITActionPerformed
    EMapel matkul = new EMapel();
    matkul.setidmpel(jTextField1_idmatkul.getText());
    matkul.setnamamapel(jTextField2_namamatkul.getText());
    matkul.setnip(comboGURU.getItemAt(comboGURU.getSelectedIndex()).toString());
    
    cCari control = new cCari();
    control.ubahmatkul(matkul);
    tabelmatkul();
        B_RESETActionPerformed(evt);
    
    }//GEN-LAST:event_B_EDITActionPerformed

    private void B_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HAPUSActionPerformed
     int pertanyaan = JOptionPane.showConfirmDialog(null,"Yakin Data ini mau dihapus ... ?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("Kamu menekan tombol CANCEL");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
          
          EMapel matkul = new EMapel();
    matkul.setidmpel(jTextField1_idmatkul.getText());
    
    cCari control = new cCari();
    control.hapusmatkul(matkul);
    tabelmatkul();
        System.out.println("Anda Menghapus data");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("Kamu menekan tombol CLOSE");
}
        
        B_RESETActionPerformed(evt);
    }//GEN-LAST:event_B_HAPUSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Form_Menu tampil;
    tampil=new Form_Menu();
    tampil.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1_tabmatkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_tabmatkulMouseClicked
    int baris = jTable1_tabmatkul.getSelectedRow();
    if(baris==-1){
        JOptionPane.showMessageDialog(this, "Pilih Data");
    }else{
     jTextField1_idmatkul.setText((String)jTable1_tabmatkul.getValueAt(baris, 0));
     jTextField2_namamatkul.setText((String)jTable1_tabmatkul.getValueAt(baris, 1));
     comboGURU.setSelectedItem((String)jTable1_tabmatkul.getValueAt(baris, 2)); 
     
    }
    }//GEN-LAST:event_jTable1_tabmatkulMouseClicked

    private void B_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RESETActionPerformed
    jTextField1_idmatkul.setText("");
    jTextField2_namamatkul.setText("");
    comboGURU.setSelectedItem("Guru");
    }//GEN-LAST:event_B_RESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MaPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MaPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MaPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MaPel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_MaPel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_EDIT;
    private javax.swing.JButton B_HAPUS;
    private javax.swing.JButton B_RESET;
    private javax.swing.JButton B_TAMBAH;
    private javax.swing.JComboBox comboGURU;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_tabmatkul;
    private javax.swing.JTextField jTextField1_idmatkul;
    private javax.swing.JTextField jTextField2_namamatkul;
    // End of variables declaration//GEN-END:variables
}
