/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TB_040_048;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TB_040_048.koneksi;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author user
 */
public class Form_WaliKelas extends javax.swing.JFrame {

    /**
     * Creates new form Form_WaliKelas
     */
    public Form_WaliKelas() {
        initComponents();
        tabelWALI();
        tampil_combo();
    }
     public void tampil_combo()
    {
        
      
        try {
        Connection conn = koneksi.getConnection();
        Statement sttm = conn.createStatement();
        String sql = "select NIP from GURU order by NIP asc";      // disini saya menampilkan NIM, anda dapat menampilkan
        ResultSet reslt = sttm.executeQuery(sql);                                // yang anda ingin kan
        
        while(reslt.next()){
            Object[] ob = new Object[3];
            ob[0] = reslt.getString(1);
            
            comboGURU.addItem(ob[0]);                                      // fungsi ini bertugas menampung isi dari database
        }
        reslt.close(); sttm.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
     
      

    
    public void tabelWALI(){
        DefaultTableModel tabbrg = new DefaultTableModel();
        tabbrg.addColumn("IDWK");
        tabbrg.addColumn("NIP");
        tabbrg.addColumn("KELAS");
        
        jTable1_waliKelas.setModel(tabbrg);
        
        try {
            Statement stat = (Statement)koneksi.getConnection().createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM WALIKELAS order by idwk asc");
            while (result.next()){
                tabbrg.addRow(new Object[]{
                    result.getString("IDWK"),
                    result.getString("NIP"), 
                    result.getString("KELAS"),
                });
                jTable1_waliKelas.setModel(tabbrg);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditampilkan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_TAMBAH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_waliKelas = new javax.swing.JTable();
        jTextField3_kelas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4_RESET = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1_idwk = new javax.swing.JTextField();
        jButton2_EDIT = new javax.swing.JButton();
        jButton3_HAPUS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboGURU = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1_TAMBAH.setText("TAMBAH");
        jButton1_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_TAMBAHActionPerformed(evt);
            }
        });

        jTable1_waliKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_waliKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_waliKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_waliKelas);

        jLabel2.setText("ID Wali Kelas");

        jLabel3.setText("NIP");

        jLabel4.setText("Kelas");

        jButton4_RESET.setText("RESET");
        jButton4_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_RESETActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2_EDIT.setText("EDIT");
        jButton2_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_EDITActionPerformed(evt);
            }
        });

        jButton3_HAPUS.setText("HAPUS");
        jButton3_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_HAPUSActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATA WALI KELAS");

        comboGURU.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guru" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton3_HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1_idwk)
                                            .addComponent(jTextField3_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                            .addComponent(comboGURU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27))))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_idwk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboGURU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_TAMBAH)
                    .addComponent(jButton2_EDIT)
                    .addComponent(jButton3_HAPUS)
                    .addComponent(jButton4_RESET))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_TAMBAHActionPerformed
        EWaliKelas wali = new EWaliKelas();
        wali.setidwk(jTextField1_idwk.getText());
        wali.setnip(comboGURU.getItemAt(comboGURU.getSelectedIndex()).toString());
        wali.setkelas(jTextField3_kelas.getText());

        cCari control = new cCari();
        control.tambahwali(wali);
        tabelWALI();
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton1_TAMBAHActionPerformed

    private void jTable1_waliKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_waliKelasMouseClicked
        int baris = jTable1_waliKelas.getSelectedRow();
        if(baris==-1){
            JOptionPane.showMessageDialog(this, "Pilih Data");
        }else{
            jTextField1_idwk.setText((String)jTable1_waliKelas.getValueAt(baris, 0));
            comboGURU.setSelectedItem((String)jTable1_waliKelas.getValueAt(baris, 1)); 
            jTextField3_kelas.setText((String)jTable1_waliKelas.getValueAt(baris, 2));
        }
    }//GEN-LAST:event_jTable1_waliKelasMouseClicked

    private void jButton4_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_RESETActionPerformed
        
        jTextField1_idwk.setText("");
        comboGURU.setSelectedItem("Guru"); 
        jTextField3_kelas.setText("");
    }//GEN-LAST:event_jButton4_RESETActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Form_Menu tampil;
        tampil=new Form_Menu();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_EDITActionPerformed
      EWaliKelas wali = new EWaliKelas();
        wali.setidwk(jTextField1_idwk.getText());
        wali.setnip(comboGURU.getItemAt(comboGURU.getSelectedIndex()).toString());
        wali.setkelas(jTextField3_kelas.getText());

        cCari control = new cCari();
        control.ubahwali(wali);
        tabelWALI();
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton2_EDITActionPerformed

    private void jButton3_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_HAPUSActionPerformed
      int pertanyaan = JOptionPane.showConfirmDialog(null,"Yakin Data ini mau dihapus ... ?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("Kamu menekan tombol CANCEL");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
      EWaliKelas wali = new EWaliKelas();
        wali.setidwk(jTextField1_idwk.getText());
        

        cCari control = new cCari();
        control.hapuswali(wali);
        tabelWALI();
        System.out.println("Anda Menghapus data");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("Kamu menekan tombol CLOSE");
}
       
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton3_HAPUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_WaliKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_WaliKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_WaliKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_WaliKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_WaliKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboGURU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_TAMBAH;
    private javax.swing.JButton jButton2_EDIT;
    private javax.swing.JButton jButton3_HAPUS;
    private javax.swing.JButton jButton4_RESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_waliKelas;
    private javax.swing.JTextField jTextField1_idwk;
    private javax.swing.JTextField jTextField3_kelas;
    // End of variables declaration//GEN-END:variables
}
