/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TB_040_048;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class Form_Murid extends javax.swing.JFrame {
    
    /*private Connection conn;
    private Statement stt;
    private ResultSet res;*/

    /**
     * Creates new form Form_Mahasiswa
     */
    public Form_Murid() {
        initComponents();
        tabelmhs();
        //koneksi();
    }
    
    public void tabelmhs(){
        DefaultTableModel tabbrg = new DefaultTableModel();
        tabbrg.addColumn("NIS");
        tabbrg.addColumn("Nama");
        tabbrg.addColumn("Alamat");
        tabbrg.addColumn("Gender");
        jTable1_tabmhs.setModel(tabbrg);
        
        try {
            Statement stat = (Statement)koneksi.getConnection().createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM SISWA order by nis asc");
            while (result.next()){
                tabbrg.addRow(new Object[]{
                    result.getString("NIS"),
                    result.getString("NAMA"),
                    result.getString("ALAMAT"),              
                    result.getString("GENDER"),
                });
                jTable1_tabmhs.setModel(tabbrg);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditampilkan");
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    /*private void koneksi(){
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","dB1","dB1");
            stt = conn.createStatement();
            System.out.println("Koneksi Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal");
        }
    } */
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_txtNO_ID = new javax.swing.JTextField();
        jTextField2_NAMA = new javax.swing.JTextField();
        jTextField3_ALAMAT = new javax.swing.JTextField();
        CARI = new javax.swing.JButton();
        B_TAMBAH = new javax.swing.JButton();
        B_EDIT = new javax.swing.JButton();
        B_HAPUS = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField4_GENDER = new javax.swing.JTextField();
        B_RESET = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabmhs = new javax.swing.JTable();
        jTextField4_cari = new javax.swing.JTextField();
        TUTUP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATA MURID");

        jLabel2.setText("NIS");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        CARI.setText("CARI");
        CARI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARIMouseClicked(evt);
            }
        });
        CARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARIActionPerformed(evt);
            }
        });

        B_TAMBAH.setText("TAMBAH");
        B_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TAMBAHActionPerformed(evt);
            }
        });

        B_EDIT.setText("EDIT");
        B_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EDITActionPerformed(evt);
            }
        });

        B_HAPUS.setText("HAPUS");
        B_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HAPUSActionPerformed(evt);
            }
        });

        jLabel6.setText("Gender");

        B_RESET.setText("RESET");
        B_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RESETActionPerformed(evt);
            }
        });

        jTable1_tabmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_tabmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_tabmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_tabmhs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_txtNO_ID)
                                    .addComponent(jTextField2_NAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3_ALAMAT, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(jTextField4_GENDER))))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(B_TAMBAH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CARI, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(B_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_txtNO_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2_NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3_ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_TAMBAH)
                    .addComponent(B_EDIT)
                    .addComponent(B_HAPUS)
                    .addComponent(B_RESET))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CARI)
                    .addComponent(jTextField4_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TUTUP.setText("TUTUP");
        TUTUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TUTUPMouseClicked(evt);
            }
        });
        TUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUTUPActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TUTUP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TUTUP)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARIActionPerformed
          DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIM");
        model.addColumn("NAMA");
        model.addColumn("ALAMAT");
        model.addColumn("GENDER");
        try {
            String cari = jTextField4_cari.getText();
            String url = "jdbc:oracle:thin:@localhost:1521:XE";
            String username = "oop";
            String password = "rail";
            
            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
            Connection conn = DriverManager.getConnection(url,username,password);
            Statement stt = conn.createStatement();
            String sql =  "select * from siswa where nis LIKE '%"+cari+"%' or "
                    +"nama LIKE '%"+cari+"%' order by nis asc";
            ResultSet res = stt.executeQuery(sql);
              while(res.next()){
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            jTable1_tabmhs.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data");
            
        }
   
    }//GEN-LAST:event_CARIActionPerformed

    private void CARIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARIMouseClicked
     
    }//GEN-LAST:event_CARIMouseClicked

    private void B_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RESETActionPerformed
    jTextField1_txtNO_ID.setText("");
    jTextField2_NAMA.setText("");
    jTextField3_ALAMAT.setText("");
    jTextField4_GENDER.setText("");
    jTextField4_cari.setText("");
    }//GEN-LAST:event_B_RESETActionPerformed

    private void TUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUTUPActionPerformed
      int pertanyaan = JOptionPane.showConfirmDialog(null,"Yakin akan menutup aplikasi ... ?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
         System.exit(0);
        System.out.println("");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("");
}
    }//GEN-LAST:event_TUTUPActionPerformed

    private void B_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TAMBAHActionPerformed
    EMurid mhs = new EMurid();
    mhs.setid(jTextField1_txtNO_ID.getText());
    mhs.setnama(jTextField2_NAMA.getText());
    mhs.setalamat(jTextField3_ALAMAT.getText());
    mhs.setgender(jTextField4_GENDER.getText());
    
    cCari control = new cCari();
    control.tambahmhs(mhs);
    
    tabelmhs();
        B_RESETActionPerformed(evt);
    }//GEN-LAST:event_B_TAMBAHActionPerformed

    private void B_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EDITActionPerformed
    EMurid mhs = new EMurid();
    mhs.setid(jTextField1_txtNO_ID.getText());
    mhs.setnama(jTextField2_NAMA.getText());
    mhs.setalamat(jTextField3_ALAMAT.getText());
    mhs.setgender(jTextField4_GENDER.getText());
    
    cCari control= new cCari();
    control.ubahmhs(mhs);
    tabelmhs();
        B_RESETActionPerformed(evt);
    }//GEN-LAST:event_B_EDITActionPerformed

    private void B_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HAPUSActionPerformed
  int pertanyaan = JOptionPane.showConfirmDialog(null,"Yakin Data ini mau dihapus ... ?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("Kamu menekan tombol CANCEL");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
         EMurid mhs = new EMurid();
    mhs.setid(jTextField1_txtNO_ID.getText());
    
    cCari control = new cCari();
    control.hapusmhs(mhs);
    tabelmhs();
        System.out.println("Anda Menghapus data");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("Kamu menekan tombol CLOSE");
}
      
        B_RESETActionPerformed(evt);
    }//GEN-LAST:event_B_HAPUSActionPerformed

    private void jTable1_tabmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_tabmhsMouseClicked
    int baris = jTable1_tabmhs.getSelectedRow();
    if(baris==-1){
        JOptionPane.showMessageDialog(this, "Pilih Data");
    }else{
     jTextField1_txtNO_ID.setText((String)jTable1_tabmhs.getValueAt(baris, 0));
     jTextField2_NAMA.setText((String)jTable1_tabmhs.getValueAt(baris, 1));
     jTextField3_ALAMAT.setText((String)jTable1_tabmhs.getValueAt(baris, 2));
     jTextField4_GENDER.setText((String)jTable1_tabmhs.getValueAt(baris, 3));
    }
    }//GEN-LAST:event_jTable1_tabmhsMouseClicked

    private void TUTUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TUTUPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TUTUPMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Form_Menu tampil;
    tampil=new Form_Menu();
    tampil.setVisible(true);
    this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Murid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Murid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Murid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Murid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Murid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_EDIT;
    private javax.swing.JButton B_HAPUS;
    private javax.swing.JButton B_RESET;
    private javax.swing.JButton B_TAMBAH;
    private javax.swing.JButton CARI;
    private javax.swing.JButton TUTUP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_tabmhs;
    private javax.swing.JTextField jTextField1_txtNO_ID;
    private javax.swing.JTextField jTextField2_NAMA;
    private javax.swing.JTextField jTextField3_ALAMAT;
    private javax.swing.JTextField jTextField4_GENDER;
    private javax.swing.JTextField jTextField4_cari;
    // End of variables declaration//GEN-END:variables
}
