/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TB_040_048;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TB_040_048.koneksi;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import TB_040_048.ENilai;
import TB_040_048.cCari;


/**
 *
 *
 */
public class Form_Nilai extends javax.swing.JFrame {

    /**
     * Creates new form Form_Nilai
     */
    public Form_Nilai() {
        initComponents();
        tabelnilai();
        tampil_combo();
        tampil_combo_mapel();
        kosong();
    }
    
    public void kosong(){
        jTextField1_no.setText("");
    comboNIS.setSelectedItem("Siswa");
    comboMAPEL.setSelectedItem("Mata Pelajaran");
    jTextField3_nilai.setText("");
    }
     public void tampil_combo()
    {
        
      
        try {
        Connection conn = koneksi.getConnection();
        Statement sttm = conn.createStatement();
        String sql = "select NIS from SISWA order by NIS asc";      // disini saya menampilkan NIM, anda dapat menampilkan
        ResultSet reslt = sttm.executeQuery(sql);                                // yang anda ingin kan
        
        while(reslt.next()){
            Object[] ob = new Object[3];
            ob[0] = reslt.getString(1);
            
            comboNIS.addItem(ob[0]);                                      // fungsi ini bertugas menampung isi dari database
        }
        reslt.close(); sttm.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
     
      public void tampil_combo_mapel()
    {
        
        try {
        Connection conn = koneksi.getConnection();
        Statement sttm = conn.createStatement();
        String sql = "select no_mapel from mapel order by no_mapel asc";      // disini saya menampilkan NIM, anda dapat menampilkan
        ResultSet reslt = sttm.executeQuery(sql);                                // yang anda ingin kan
        
        while(reslt.next()){
            Object[] ob = new Object[3];
            ob[0] = reslt.getString(1);
            
            comboMAPEL.addItem(ob[0]);                                      // fungsi ini bertugas menampung isi dari database
        }
        reslt.close(); sttm.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    
    public void tabelnilai(){
        DefaultTableModel tabbrg = new DefaultTableModel();
        tabbrg.addColumn("NO");
        tabbrg.addColumn("NIS");
        tabbrg.addColumn("NO Mata Pelajaran");
        tabbrg.addColumn("Nilai");
        
        jTable1_nilai.setModel(tabbrg);
        
        try {
            Statement stat = (Statement)koneksi.getConnection().createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM NILAI order by nO asc");
            while (result.next()){
                tabbrg.addRow(new Object[]{
                    result.getString("NO"),
                    result.getString("NIS"),
                    result.getString("NO_MAPEL"), 
                    result.getString("NILAI"),
                });
                jTable1_nilai.setModel(tabbrg);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditampilkan");
        }
    }
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3_nilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_nilai = new javax.swing.JTable();
        jButton1_TAMBAH = new javax.swing.JButton();
        jButton2_UBAH = new javax.swing.JButton();
        jButton3_HAPUS = new javax.swing.JButton();
        jButton4_RESET = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        comboNIS = new javax.swing.JComboBox();
        comboMAPEL = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_no = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DATA NILAI MURID");

        jLabel2.setText("NIS");

        jLabel3.setText("NO MaPel");

        jLabel4.setText("Nilai");

        jTable1_nilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_nilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_nilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_nilai);

        jButton1_TAMBAH.setText("TAMBAH");
        jButton1_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_TAMBAHActionPerformed(evt);
            }
        });

        jButton2_UBAH.setText("UBAH");
        jButton2_UBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_UBAHActionPerformed(evt);
            }
        });

        jButton3_HAPUS.setText("HAPUS");
        jButton3_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_HAPUSActionPerformed(evt);
            }
        });

        jButton4_RESET.setText("RESET");
        jButton4_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_RESETActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboNIS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Siswa" }));

        comboMAPEL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mata Pelajaran" }));

        jLabel5.setText("No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3_nilai)
                                    .addComponent(comboNIS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboMAPEL, 0, 177, Short.MAX_VALUE)
                                    .addComponent(jTextField1_no)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2_UBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3_HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboMAPEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_TAMBAH)
                    .addComponent(jButton2_UBAH)
                    .addComponent(jButton3_HAPUS)
                    .addComponent(jButton4_RESET))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_TAMBAHActionPerformed
    ENilai nilai = new ENilai();
    nilai.setno(jTextField1_no.getText());
    nilai.setnis(comboNIS.getItemAt(comboNIS.getSelectedIndex()).toString());
    nilai.setidmapel(comboMAPEL.getItemAt(comboMAPEL.getSelectedIndex()).toString());
    nilai.setnilai(Integer.parseInt(jTextField3_nilai.getText()));
    
    cCari control = new cCari();
    control.tambahnilai(nilai);
    tabelnilai();
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton1_TAMBAHActionPerformed

    private void jButton2_UBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_UBAHActionPerformed
    ENilai nilai = new ENilai();
    nilai.setno(jTextField1_no.getText());
    nilai.setnis(comboNIS.getItemAt(comboNIS.getSelectedIndex()).toString());
    nilai.setidmapel(comboMAPEL.getItemAt(comboMAPEL.getSelectedIndex()).toString());
    nilai.setnilai(Integer.parseInt(jTextField3_nilai.getText()));
    
    cCari control = new cCari();
    control.ubahnilai(nilai);
    tabelnilai();
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton2_UBAHActionPerformed

    private void jButton3_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_HAPUSActionPerformed
    int pertanyaan = JOptionPane.showConfirmDialog(null,"Yakin Data ini mau dihapus ... ?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("Kamu menekan tombol CANCEL");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
       ENilai nilai = new ENilai();
    nilai.setno(jTextField1_no.getText());
   
    
    cCari control = new cCari();
    control.hapusnilai(nilai);
    tabelnilai();
        System.out.println("Anda Menghapus data");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("Kamu menekan tombol CLOSE");
}
        
        jButton4_RESETActionPerformed(evt);
    }//GEN-LAST:event_jButton3_HAPUSActionPerformed

    private void jButton4_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_RESETActionPerformed
    kosong();
    }//GEN-LAST:event_jButton4_RESETActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Form_Menu tampil;
    tampil=new Form_Menu();
    tampil.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1_nilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_nilaiMouseClicked
    int baris = jTable1_nilai.getSelectedRow();
    if(baris==-1){
        JOptionPane.showMessageDialog(this, "Pilih Data");
    }else{
      jTextField1_no.setText((String)jTable1_nilai.getValueAt(baris, 0));
     comboNIS.setSelectedItem((String)jTable1_nilai.getValueAt(baris, 1)); 
     comboMAPEL.setSelectedItem((String)jTable1_nilai.getValueAt(baris, 2)); 
     jTextField3_nilai.setText((String)jTable1_nilai.getValueAt(baris, 3));
    }
    }//GEN-LAST:event_jTable1_nilaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboMAPEL;
    private javax.swing.JComboBox comboNIS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_TAMBAH;
    private javax.swing.JButton jButton2_UBAH;
    private javax.swing.JButton jButton3_HAPUS;
    private javax.swing.JButton jButton4_RESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_nilai;
    private javax.swing.JTextField jTextField1_no;
    private javax.swing.JTextField jTextField3_nilai;
    // End of variables declaration//GEN-END:variables
}
