/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TB_040_048;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Form_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Form_Menu
     */
    public Form_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TUTUP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        M_MURID = new javax.swing.JButton();
        M_MAPEL = new javax.swing.JButton();
        M_NILAI = new javax.swing.JButton();
        M_GURU = new javax.swing.JButton();
        M_KELAS = new javax.swing.JButton();
        M_WALI = new javax.swing.JButton();
        M_ESKUL = new javax.swing.JButton();
        TUTUP1 = new javax.swing.JButton();
        jButton1_LogOut = new javax.swing.JButton();

        TUTUP.setText("TUTUP");
        TUTUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TUTUPMouseClicked(evt);
            }
        });
        TUTUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUTUPActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("MENU");

        M_MURID.setText("MURID");
        M_MURID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_MURIDActionPerformed(evt);
            }
        });

        M_MAPEL.setText("MATA PELAJARAN");
        M_MAPEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                M_MAPELMouseClicked(evt);
            }
        });
        M_MAPEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_MAPELActionPerformed(evt);
            }
        });

        M_NILAI.setText("NILAI");
        M_NILAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_NILAIActionPerformed(evt);
            }
        });

        M_GURU.setText("GURU");
        M_GURU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_GURUActionPerformed(evt);
            }
        });

        M_KELAS.setText("KELAS");
        M_KELAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_KELASActionPerformed(evt);
            }
        });

        M_WALI.setText("WALI KELAS");
        M_WALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_WALIActionPerformed(evt);
            }
        });

        M_ESKUL.setText("EKSTRAKULIKULER");
        M_ESKUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_ESKULActionPerformed(evt);
            }
        });

        TUTUP1.setText("TUTUP");
        TUTUP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TUTUP1MouseClicked(evt);
            }
        });
        TUTUP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUTUP1ActionPerformed(evt);
            }
        });

        jButton1_LogOut.setText("Log Out");
        jButton1_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(M_KELAS, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(M_NILAI, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(M_MAPEL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(M_WALI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(M_MURID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(M_GURU, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TUTUP1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1_LogOut))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(M_ESKUL)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TUTUP1)
                            .addComponent(jButton1_LogOut))))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_NILAI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_MAPEL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_MURID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_GURU, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_KELAS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(M_WALI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(M_ESKUL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void M_MURIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_MURIDActionPerformed
        Form_Murid tampil;
        tampil=new Form_Murid();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_MURIDActionPerformed

    private void M_MAPELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_M_MAPELMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_M_MAPELMouseClicked

    private void M_MAPELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_MAPELActionPerformed
        Form_MaPel tampil;
        tampil=new Form_MaPel();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_MAPELActionPerformed

    private void M_NILAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_NILAIActionPerformed
        Form_Nilai tampil;
        tampil=new Form_Nilai();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_NILAIActionPerformed

    private void M_GURUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_GURUActionPerformed
        // TODO add your handling code here:
        Form_Guru tampil;
        tampil=new Form_Guru();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_GURUActionPerformed

    private void M_KELASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_KELASActionPerformed
        // TODO add your handling code here:
        Form_Kelas tampil;
        tampil=new Form_Kelas();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_KELASActionPerformed

    private void M_WALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_WALIActionPerformed
        // TODO add your handling code here:
        Form_WaliKelas tampil;
        tampil=new Form_WaliKelas();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_WALIActionPerformed

    private void M_ESKULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_ESKULActionPerformed
        // TODO add your handling code here:
        Form_Ekskul tampil;
        tampil=new Form_Ekskul();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_M_ESKULActionPerformed

    private void TUTUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TUTUPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TUTUPMouseClicked

    private void TUTUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUTUPActionPerformed
     
    }//GEN-LAST:event_TUTUPActionPerformed

    private void TUTUP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TUTUP1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TUTUP1MouseClicked

    private void TUTUP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUTUP1ActionPerformed
         int pertanyaan = JOptionPane.showConfirmDialog(null,"Yakin akan menutup aplikasi ... ?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
         System.exit(0);
        System.out.println("");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("");
}
   
    }//GEN-LAST:event_TUTUP1ActionPerformed

    private void jButton1_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LogOutActionPerformed
        // TODO add your handling code here:
          int pertanyaan = JOptionPane.showConfirmDialog(null,"Log Out  ... ?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
          Login tampil;
        tampil=new Login();
        tampil.setVisible(true);
        this.dispose();
        System.out.println("");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("");
}
      
    }//GEN-LAST:event_jButton1_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton M_ESKUL;
    private javax.swing.JButton M_GURU;
    private javax.swing.JButton M_KELAS;
    private javax.swing.JButton M_MAPEL;
    private javax.swing.JButton M_MURID;
    private javax.swing.JButton M_NILAI;
    private javax.swing.JButton M_WALI;
    private javax.swing.JButton TUTUP;
    private javax.swing.JButton TUTUP1;
    private javax.swing.JButton jButton1_LogOut;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
