/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TB_040_048;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import TB_040_048.EMapel;
import TB_040_048.cCari;


/**
 *
 * @author user
 */
public class Form_Guru extends javax.swing.JFrame {

    /**
     * Creates new form Form_Guru
     */
    public Form_Guru() {
        initComponents();
        tabelguru();
    }
     public void tabelguru(){
        DefaultTableModel tabbrg = new DefaultTableModel();
        tabbrg.addColumn("NIP");
        tabbrg.addColumn("Nama");
        tabbrg.addColumn("Alamat");
        tabbrg.addColumn("Gender");
        
        jTable1_tabguru.setModel(tabbrg);
        
        try {
            Statement stat = (Statement)koneksi.getConnection().createStatement();
            ResultSet result = stat.executeQuery("SELECT * FROM GURU ORDER BY NIP ASC");
            while (result.next()){
                tabbrg.addRow(new Object[]{
                    result.getString("NIP"),
                    result.getString("NAMA"),
                    result.getString("ALAMAT"),
                    result.getString("GENDER"),              
                });
                jTable1_tabguru.setModel(tabbrg);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditampilkan");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_NIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2_NAMA = new javax.swing.JTextField();
        B_TAMBAH = new javax.swing.JButton();
        B_HAPUS = new javax.swing.JButton();
        B_EDIT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        B_RESET = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3_ALAMAT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_tabguru = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField4_GENDER = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA GURU");

        jLabel2.setText("NIP");

        jLabel3.setText("NAMA");

        B_TAMBAH.setText("TAMBAH");
        B_TAMBAH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_TAMBAHMouseClicked(evt);
            }
        });
        B_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_TAMBAHActionPerformed(evt);
            }
        });

        B_HAPUS.setText("HAPUS");
        B_HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HAPUSActionPerformed(evt);
            }
        });

        B_EDIT.setText("EDIT");
        B_EDIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_EDITMouseClicked(evt);
            }
        });
        B_EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EDITActionPerformed(evt);
            }
        });

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        B_RESET.setText("RESET");
        B_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RESETActionPerformed(evt);
            }
        });

        jTable1_tabguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_tabguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_tabguruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_tabguru);

        jLabel5.setText("Alamat");

        jLabel6.setText("Gender");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2_NAMA)
                                    .addComponent(jTextField3_ALAMAT)
                                    .addComponent(jTextField4_GENDER)
                                    .addComponent(jTextField1_NIP, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(B_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_NIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2_NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3_ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4_GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_TAMBAH)
                    .addComponent(B_EDIT)
                    .addComponent(B_HAPUS)
                    .addComponent(B_RESET))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_TAMBAHActionPerformed
        EGuru guru = new EGuru();
        guru.setid(jTextField1_NIP.getText());
        guru.setnama(jTextField2_NAMA.getText());
        guru.setalamat(jTextField3_ALAMAT.getText());
        guru.setgender(jTextField4_GENDER.getText());   
        cCari control = new cCari();
        control.tambahguru(guru);
        tabelguru();
        B_RESETActionPerformed(evt);
    }//GEN-LAST:event_B_TAMBAHActionPerformed

    private void B_HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HAPUSActionPerformed
        int pertanyaan = JOptionPane.showConfirmDialog(null,"Yakin Data ini mau dihapus ... ?","Konfimasi",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(pertanyaan == JOptionPane.CANCEL_OPTION){
      System.out.println("Kamu menekan tombol CANCEL");
      }else if(pertanyaan == JOptionPane.OK_OPTION){
          
            EGuru guru = new EGuru();
        guru.setid(jTextField1_NIP.getText());

        cCari control = new cCari();
        control.hapusguru(guru);
        tabelguru();
        System.out.println("Anda Menghapus data");
      }else if(pertanyaan == JOptionPane.CLOSED_OPTION){
      System.out.println("Kamu menekan tombol CLOSE");
}
       
       
      
        B_RESETActionPerformed(evt);
    }//GEN-LAST:event_B_HAPUSActionPerformed

    private void B_EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EDITActionPerformed
        EGuru guru = new EGuru();
        guru.setid(jTextField1_NIP.getText());
        guru.setnama(jTextField2_NAMA.getText());
        guru.setalamat(jTextField3_ALAMAT.getText());
        guru.setgender(jTextField4_GENDER.getText());

        cCari control = new cCari();
        control.ubahguru(guru);
        tabelguru();
        B_RESETActionPerformed(evt);

    }//GEN-LAST:event_B_EDITActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Form_Menu tampil;
        tampil=new Form_Menu();
        tampil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RESETActionPerformed
        jTextField1_NIP.setText("");
        jTextField2_NAMA.setText("");
        jTextField3_ALAMAT.setText("");
        jTextField4_GENDER.setText("");
    }//GEN-LAST:event_B_RESETActionPerformed

    private void jTable1_tabguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_tabguruMouseClicked
        int baris = jTable1_tabguru.getSelectedRow();
        if(baris==-1){
            JOptionPane.showMessageDialog(this, "Pilih Data");
        }else{
            jTextField1_NIP.setText((String)jTable1_tabguru.getValueAt(baris, 0));
            jTextField2_NAMA.setText((String)jTable1_tabguru.getValueAt(baris, 1));
            jTextField3_ALAMAT.setText((String)jTable1_tabguru.getValueAt(baris, 2));
            jTextField4_GENDER.setText((String)jTable1_tabguru.getValueAt(baris, 3));
        }
    }//GEN-LAST:event_jTable1_tabguruMouseClicked

    private void B_TAMBAHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_TAMBAHMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_B_TAMBAHMouseClicked

    private void B_EDITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EDITMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_B_EDITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_EDIT;
    private javax.swing.JButton B_HAPUS;
    private javax.swing.JButton B_RESET;
    private javax.swing.JButton B_TAMBAH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_tabguru;
    private javax.swing.JTextField jTextField1_NIP;
    private javax.swing.JTextField jTextField2_NAMA;
    private javax.swing.JTextField jTextField3_ALAMAT;
    private javax.swing.JTextField jTextField4_GENDER;
    // End of variables declaration//GEN-END:variables
}
